In [1]:
import numpy as np
import pandas as pd

In [2]:
df=np.random.random(10)*10
df=np.reshape(df,(-1,1))
df.shape
df

array([[0.73624113],
       [2.14966451],
       [6.29358036],
       [4.9135792 ],
       [5.32267843],
       [2.77386016],
       [7.91851176],
       [8.42806907],
       [8.81922104],
       [8.77585393]])

In [5]:
def make_df(df,steps):
    X=[]
    Y=[]
    for i in range(len(df)):
        a=df[i]
        X.append(a)
    for i in range(len(df)-steps):
        b=df[i+steps,0]
        Y.append(b)
    return np.array(X), np.array(Y)

In [6]:
steps=3
X,Y= make_df(df,steps)

In [7]:
X

array([[0.73624113],
       [2.14966451],
       [6.29358036],
       [4.9135792 ],
       [5.32267843],
       [2.77386016],
       [7.91851176],
       [8.42806907],
       [8.81922104],
       [8.77585393]])

In [8]:
Y

array([4.9135792 , 5.32267843, 2.77386016, 7.91851176, 8.42806907,
       8.81922104, 8.77585393])

In [9]:
len(X)

10